AWSTemplateFormatVersion: '2010-09-09'
Description: Main Entrypoint to configure a Foundation Solution

Parameters:
  EnvironmentName:
    Description: Environment
    Type: String
    Default: sandbox


Resources:
  RDS:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      TemplateURL: './workloads/rds.yaml'

  Security:
   Type: 'AWS::CloudFormation::Stack'
   Properties:
     Parameters:
       EnvironmentName: !Ref EnvironmentName
     TemplateURL: './security/security-groups.yaml'
