AWSTemplateFormatVersion: '2010-09-09'
Description: Postgres RDS service

Parameters:
  EnvironmentName:
    Description: Environment
    Type: String
    Default: sandbox

Resources:

  # https://aws.amazon.com/de/blogs/security/how-to-create-and-retrieve-secrets-managed-in-aws-secrets-manager-using-aws-cloudformation-template/
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the secret for my RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "superpostgres"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join [ '-', [ !Ref EnvironmentName, test ] ]
      DBName: test
      Engine: postgres
      PubliclyAccessible: false
      EngineVersion: 13
      MultiAZ: true
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSInstanceRotationSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSInstanceRotationSecret, ':SecretString:password}}' ]]
      DBInstanceClass: db.m5.large
      AllocatedStorage: 20